version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "java:maven"
    directory: "/src"
    update_schedule: "daily"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "RealStormi"
    default_labels:
      - "bug"
