main: de.stormi.main.Main
version: 0.2
name: guard

commands:
  heal:
    description: Mit diesem Befehl kannst du dich Heilen
  shelp:
    description: Dieser Command gehört zum Guard system von Stormi_139 und zeigt dir alle Befehle an!
  adminhelp:
    descripton: §4§lNur für Admins!
  feedcommand:
    description: Stille deinen Hunger
  flyspeed1:
    description: Setzte deine Fluggeschwindigkeit auf 1
  fly:
    description: Damit kannst du im Gamemode 0 fliegen
  opheal:
    description: §4§lNur für Admins!
